// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/proto/gateway.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SensorReading struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Unit          string                 `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorReading) Reset() {
	*x = SensorReading{}
	mi := &file_api_proto_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorReading) ProtoMessage() {}

func (x *SensorReading) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorReading.ProtoReflect.Descriptor instead.
func (*SensorReading) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *SensorReading) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SensorReading) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SensorReading) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *SensorReading) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SensorReading) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type StoreReadingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reading       *SensorReading         `protobuf:"bytes,1,opt,name=reading,proto3" json:"reading,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreReadingRequest) Reset() {
	*x = StoreReadingRequest{}
	mi := &file_api_proto_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreReadingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreReadingRequest) ProtoMessage() {}

func (x *StoreReadingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreReadingRequest.ProtoReflect.Descriptor instead.
func (*StoreReadingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *StoreReadingRequest) GetReading() *SensorReading {
	if x != nil {
		return x.Reading
	}
	return nil
}

type StoreReadingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreReadingResponse) Reset() {
	*x = StoreReadingResponse{}
	mi := &file_api_proto_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreReadingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreReadingResponse) ProtoMessage() {}

func (x *StoreReadingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreReadingResponse.ProtoReflect.Descriptor instead.
func (*StoreReadingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *StoreReadingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreReadingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StoreBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Readings      []*SensorReading       `protobuf:"bytes,1,rep,name=readings,proto3" json:"readings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreBatchRequest) Reset() {
	*x = StoreBatchRequest{}
	mi := &file_api_proto_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreBatchRequest) ProtoMessage() {}

func (x *StoreBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreBatchRequest.ProtoReflect.Descriptor instead.
func (*StoreBatchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *StoreBatchRequest) GetReadings() []*SensorReading {
	if x != nil {
		return x.Readings
	}
	return nil
}

type StoreBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreBatchResponse) Reset() {
	*x = StoreBatchResponse{}
	mi := &file_api_proto_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreBatchResponse) ProtoMessage() {}

func (x *StoreBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreBatchResponse.ProtoReflect.Descriptor instead.
func (*StoreBatchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *StoreBatchResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *StoreBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_proto_gateway_proto protoreflect.FileDescriptor

const file_api_proto_gateway_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/gateway.proto\x12\agateway\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa4\x01\n" +
	"\rSensorReading\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04unit\x18\x05 \x01(\tR\x04unit\"G\n" +
	"\x13StoreReadingRequest\x120\n" +
	"\areading\x18\x01 \x01(\v2\x16.gateway.SensorReadingR\areading\"J\n" +
	"\x14StoreReadingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"G\n" +
	"\x11StoreBatchRequest\x122\n" +
	"\breadings\x18\x01 \x03(\v2\x16.gateway.SensorReadingR\breadings\"D\n" +
	"\x12StoreBatchResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2\xa4\x01\n" +
	"\x0eStorageService\x12K\n" +
	"\fStoreReading\x12\x1c.gateway.StoreReadingRequest\x1a\x1d.gateway.StoreReadingResponse\x12E\n" +
	"\n" +
	"StoreBatch\x12\x1a.gateway.StoreBatchRequest\x1a\x1b.gateway.StoreBatchResponseB-Z+github.com/k1tasun/GoEdge-Gateway/api/protob\x06proto3"

var (
	file_api_proto_gateway_proto_rawDescOnce sync.Once
	file_api_proto_gateway_proto_rawDescData []byte
)

func file_api_proto_gateway_proto_rawDescGZIP() []byte {
	file_api_proto_gateway_proto_rawDescOnce.Do(func() {
		file_api_proto_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_gateway_proto_rawDesc), len(file_api_proto_gateway_proto_rawDesc)))
	})
	return file_api_proto_gateway_proto_rawDescData
}

var file_api_proto_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_gateway_proto_goTypes = []any{
	(*SensorReading)(nil),         // 0: gateway.SensorReading
	(*StoreReadingRequest)(nil),   // 1: gateway.StoreReadingRequest
	(*StoreReadingResponse)(nil),  // 2: gateway.StoreReadingResponse
	(*StoreBatchRequest)(nil),     // 3: gateway.StoreBatchRequest
	(*StoreBatchResponse)(nil),    // 4: gateway.StoreBatchResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_api_proto_gateway_proto_depIdxs = []int32{
	5, // 0: gateway.SensorReading.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: gateway.StoreReadingRequest.reading:type_name -> gateway.SensorReading
	0, // 2: gateway.StoreBatchRequest.readings:type_name -> gateway.SensorReading
	1, // 3: gateway.StorageService.StoreReading:input_type -> gateway.StoreReadingRequest
	3, // 4: gateway.StorageService.StoreBatch:input_type -> gateway.StoreBatchRequest
	2, // 5: gateway.StorageService.StoreReading:output_type -> gateway.StoreReadingResponse
	4, // 6: gateway.StorageService.StoreBatch:output_type -> gateway.StoreBatchResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_gateway_proto_init() }
func file_api_proto_gateway_proto_init() {
	if File_api_proto_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_gateway_proto_rawDesc), len(file_api_proto_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_gateway_proto_goTypes,
		DependencyIndexes: file_api_proto_gateway_proto_depIdxs,
		MessageInfos:      file_api_proto_gateway_proto_msgTypes,
	}.Build()
	File_api_proto_gateway_proto = out.File
	file_api_proto_gateway_proto_goTypes = nil
	file_api_proto_gateway_proto_depIdxs = nil
}
